/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MinecraftOrder {
    id: string;
    paymentStatus: string;
    customer?: string;
    owner: Principal;
    totalAmount: bigint;
    timestamp: bigint;
    items: Array<CartItem>;
    upiPaymentReference?: string;
}
export interface UpiTransaction {
    transactionReference: string;
    owner: Principal;
    timestamp: bigint;
    upiId: string;
    amount: bigint;
}
export interface AdminToken {
    token: string;
    expiresAt: bigint;
    revoked: boolean;
    usedBy?: Principal;
    createdAt: bigint;
    createdBy: Principal;
    used: boolean;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ServerStatus {
    playerCount: bigint;
    message: string;
    timestamp: bigint;
    online: boolean;
}
export interface PendingPromotion {
    token: string;
    user: Principal;
    requestedAt: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PaymentSuccessResponse {
    message: string;
    payment: {
        status: string;
        paymentMethod: {
            last4: string;
            brand: string;
        };
        currency: string;
        amount: bigint;
    };
}
export interface UserRoleInfo {
    isModerator: boolean;
    principal: Principal;
    isAdmin: boolean;
}
export interface UpiQrTransaction {
    status: string;
    transactionReference: string;
    owner: Principal;
    timestamp: bigint;
    amount: bigint;
    qrCode: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PaymentCancelResponse {
    message: string;
    sessionId: string;
}
export interface CartItem {
    productId: string;
    quantity: bigint;
}
export interface Product {
    id: string;
    name: string;
    description: string;
    available: boolean;
    upiAmount: bigint;
    category: ProductCategory;
}
export interface UserProfile {
    name: string;
    email: string;
    minecraftUsername: string;
}
export enum ProductCategory {
    perk = "perk",
    rank = "rank",
    crateKey = "crateKey"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(id: string, name: string, description: string, category: ProductCategory, upiAmount: bigint, available: boolean): Promise<void>;
    addUpiTransaction(transactionReference: string, upiId: string, amount: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignModeratorRole(user: Principal): Promise<void>;
    confirmUpiPaymentUsingQr(transactionReference: string): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    fetchServerStatus(): Promise<string>;
    generateAdminToken(): Promise<string>;
    generateUpiQr(cartItems: Array<CartItem>, customer: string): Promise<string>;
    getActiveAdminTokens(): Promise<Array<AdminToken>>;
    getActiveUpiQrs(): Promise<Array<UpiQrTransaction>>;
    getAdminToken(token: string): Promise<AdminToken>;
    getAdminUpiId(): Promise<string>;
    getAllAdminTokens(): Promise<Array<AdminToken>>;
    getAllModerators(): Promise<Array<Principal>>;
    getCachedStatus(): Promise<ServerStatus | null>;
    getCallerOrders(): Promise<Array<MinecraftOrder>>;
    getCallerRole(): Promise<UserRoleInfo>;
    getCallerUpiTransactions(): Promise<Array<UpiTransaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getOrder(id: string): Promise<MinecraftOrder>;
    getOrders(): Promise<Array<MinecraftOrder>>;
    getPendingPromotions(): Promise<Array<PendingPromotion>>;
    getPrincipalInfo(): Promise<string>;
    getProduct(id: string): Promise<Product>;
    getProducts(): Promise<Array<Product>>;
    getQrStatus(transactionReference: string): Promise<string>;
    getServerAddress(): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(user: Principal): Promise<UserRoleInfo>;
    hasPendingPromotion(): Promise<boolean>;
    initializePrices(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isPrimaryAdminAccount(): Promise<boolean>;
    paymentCancel(sessionId: string): Promise<PaymentCancelResponse>;
    paymentSuccess(sessionId: string, accountId: string, caffeineCustomerId: string): Promise<PaymentSuccessResponse>;
    processPendingPromotions(): Promise<void>;
    promoteToAdmin(user: Principal): Promise<void>;
    revokeAdminToken(token: string): Promise<void>;
    revokeModeratorRole(user: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAdminUpiId(newUpiId: string): Promise<void>;
    setCachedStatus(status: ServerStatus): Promise<void>;
    toggleProductAvailability(id: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateMinecraftUsername(minecraftUsername: string): Promise<void>;
    updateProduct(id: string, name: string, description: string, category: ProductCategory, upiAmount: bigint, available: boolean): Promise<void>;
    validateAndRequestPromotion(token: string): Promise<void>;
}
import type { AdminToken as _AdminToken, CartItem as _CartItem, MinecraftOrder as _MinecraftOrder, Product as _Product, ProductCategory as _ProductCategory, ServerStatus as _ServerStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: string, arg3: ProductCategory, arg4: bigint, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, to_candid_ProductCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, to_candid_ProductCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async addUpiTransaction(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUpiTransaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUpiTransaction(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignModeratorRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignModeratorRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignModeratorRole(arg0);
            return result;
        }
    }
    async confirmUpiPaymentUsingQr(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmUpiPaymentUsingQr(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmUpiPaymentUsingQr(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async fetchServerStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchServerStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchServerStatus();
            return result;
        }
    }
    async generateAdminToken(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAdminToken();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAdminToken();
            return result;
        }
    }
    async generateUpiQr(arg0: Array<CartItem>, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateUpiQr(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateUpiQr(arg0, arg1);
            return result;
        }
    }
    async getActiveAdminTokens(): Promise<Array<AdminToken>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAdminTokens();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAdminTokens();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveUpiQrs(): Promise<Array<UpiQrTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveUpiQrs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveUpiQrs();
            return result;
        }
    }
    async getAdminToken(arg0: string): Promise<AdminToken> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminToken(arg0);
                return from_candid_AdminToken_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminToken(arg0);
            return from_candid_AdminToken_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminUpiId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUpiId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUpiId();
            return result;
        }
    }
    async getAllAdminTokens(): Promise<Array<AdminToken>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdminTokens();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdminTokens();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllModerators(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllModerators();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllModerators();
            return result;
        }
    }
    async getCachedStatus(): Promise<ServerStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCachedStatus();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCachedStatus();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerOrders(): Promise<Array<MinecraftOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerOrders();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerOrders();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerRole(): Promise<UserRoleInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRole();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRole();
            return result;
        }
    }
    async getCallerUpiTransactions(): Promise<Array<UpiTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUpiTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUpiTransactions();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<MinecraftOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_MinecraftOrder_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_MinecraftOrder_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<MinecraftOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingPromotions(): Promise<Array<PendingPromotion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPromotions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPromotions();
            return result;
        }
    }
    async getPrincipalInfo(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrincipalInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrincipalInfo();
            return result;
        }
    }
    async getProduct(arg0: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQrStatus(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getQrStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQrStatus(arg0);
            return result;
        }
    }
    async getServerAddress(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getServerAddress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServerAddress();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: Principal): Promise<UserRoleInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return result;
        }
    }
    async hasPendingPromotion(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasPendingPromotion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasPendingPromotion();
            return result;
        }
    }
    async initializePrices(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializePrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializePrices();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isPrimaryAdminAccount(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPrimaryAdminAccount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPrimaryAdminAccount();
            return result;
        }
    }
    async paymentCancel(arg0: string): Promise<PaymentCancelResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.paymentCancel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.paymentCancel(arg0);
            return result;
        }
    }
    async paymentSuccess(arg0: string, arg1: string, arg2: string): Promise<PaymentSuccessResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.paymentSuccess(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.paymentSuccess(arg0, arg1, arg2);
            return result;
        }
    }
    async processPendingPromotions(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processPendingPromotions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processPendingPromotions();
            return result;
        }
    }
    async promoteToAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteToAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteToAdmin(arg0);
            return result;
        }
    }
    async revokeAdminToken(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeAdminToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeAdminToken(arg0);
            return result;
        }
    }
    async revokeModeratorRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeModeratorRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeModeratorRole(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAdminUpiId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminUpiId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminUpiId(arg0);
            return result;
        }
    }
    async setCachedStatus(arg0: ServerStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCachedStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCachedStatus(arg0);
            return result;
        }
    }
    async toggleProductAvailability(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleProductAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleProductAvailability(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateMinecraftUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMinecraftUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMinecraftUsername(arg0);
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: string, arg2: string, arg3: ProductCategory, arg4: bigint, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, to_candid_ProductCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, to_candid_ProductCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async validateAndRequestPromotion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAndRequestPromotion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAndRequestPromotion(arg0);
            return result;
        }
    }
}
function from_candid_AdminToken_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminToken): AdminToken {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_MinecraftOrder_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MinecraftOrder): MinecraftOrder {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServerStatus]): ServerStatus | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    paymentStatus: string;
    customer: [] | [string];
    owner: Principal;
    totalAmount: bigint;
    timestamp: bigint;
    items: Array<_CartItem>;
    upiPaymentReference: [] | [string];
}): {
    id: string;
    paymentStatus: string;
    customer?: string;
    owner: Principal;
    totalAmount: bigint;
    timestamp: bigint;
    items: Array<CartItem>;
    upiPaymentReference?: string;
} {
    return {
        id: value.id,
        paymentStatus: value.paymentStatus,
        customer: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.customer)),
        owner: value.owner,
        totalAmount: value.totalAmount,
        timestamp: value.timestamp,
        items: value.items,
        upiPaymentReference: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.upiPaymentReference))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    available: boolean;
    upiAmount: bigint;
    category: _ProductCategory;
}): {
    id: string;
    name: string;
    description: string;
    available: boolean;
    upiAmount: bigint;
    category: ProductCategory;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        available: value.available,
        upiAmount: value.upiAmount,
        category: from_candid_ProductCategory_n19(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    expiresAt: bigint;
    revoked: boolean;
    usedBy: [] | [Principal];
    createdAt: bigint;
    createdBy: Principal;
    used: boolean;
}): {
    token: string;
    expiresAt: bigint;
    revoked: boolean;
    usedBy?: Principal;
    createdAt: bigint;
    createdBy: Principal;
    used: boolean;
} {
    return {
        token: value.token,
        expiresAt: value.expiresAt,
        revoked: value.revoked,
        usedBy: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.usedBy)),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        used: value.used
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    perk: null;
} | {
    rank: null;
} | {
    crateKey: null;
}): ProductCategory {
    return "perk" in value ? ProductCategory.perk : "rank" in value ? ProductCategory.rank : "crateKey" in value ? ProductCategory.crateKey : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MinecraftOrder>): Array<MinecraftOrder> {
    return value.map((x)=>from_candid_MinecraftOrder_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminToken>): Array<AdminToken> {
    return value.map((x)=>from_candid_AdminToken_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ProductCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    perk: null;
} | {
    rank: null;
} | {
    crateKey: null;
} {
    return value == ProductCategory.perk ? {
        perk: null
    } : value == ProductCategory.rank ? {
        rank: null
    } : value == ProductCategory.crateKey ? {
        crateKey: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
