/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminToken {
  'token' : string,
  'expiresAt' : bigint,
  'revoked' : boolean,
  'usedBy' : [] | [Principal],
  'createdAt' : bigint,
  'createdBy' : Principal,
  'used' : boolean,
}
export interface CartItem { 'productId' : string, 'quantity' : bigint }
export interface MinecraftOrder {
  'id' : string,
  'paymentStatus' : string,
  'customer' : [] | [string],
  'owner' : Principal,
  'totalAmount' : bigint,
  'timestamp' : bigint,
  'items' : Array<CartItem>,
  'upiPaymentReference' : [] | [string],
}
export interface PaymentCancelResponse {
  'message' : string,
  'sessionId' : string,
}
export interface PaymentSuccessResponse {
  'message' : string,
  'payment' : {
    'status' : string,
    'paymentMethod' : { 'last4' : string, 'brand' : string },
    'currency' : string,
    'amount' : bigint,
  },
}
export interface PendingPromotion {
  'token' : string,
  'user' : Principal,
  'requestedAt' : bigint,
}
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'upiAmount' : bigint,
  'category' : ProductCategory,
}
export type ProductCategory = { 'perk' : null } |
  { 'rank' : null } |
  { 'crateKey' : null };
export interface ServerStatus {
  'playerCount' : bigint,
  'message' : string,
  'timestamp' : bigint,
  'online' : boolean,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpiQrTransaction {
  'status' : string,
  'transactionReference' : string,
  'owner' : Principal,
  'timestamp' : bigint,
  'amount' : bigint,
  'qrCode' : string,
}
export interface UpiTransaction {
  'transactionReference' : string,
  'owner' : Principal,
  'timestamp' : bigint,
  'upiId' : string,
  'amount' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'minecraftUsername' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserRoleInfo {
  'isModerator' : boolean,
  'principal' : Principal,
  'isAdmin' : boolean,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, string, ProductCategory, bigint, boolean],
    undefined
  >,
  'addUpiTransaction' : ActorMethod<[string, string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignModeratorRole' : ActorMethod<[Principal], undefined>,
  'confirmUpiPaymentUsingQr' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'fetchServerStatus' : ActorMethod<[], string>,
  'generateAdminToken' : ActorMethod<[], string>,
  'generateUpiQr' : ActorMethod<[Array<CartItem>, string], string>,
  'getActiveAdminTokens' : ActorMethod<[], Array<AdminToken>>,
  'getActiveUpiQrs' : ActorMethod<[], Array<UpiQrTransaction>>,
  'getAdminToken' : ActorMethod<[string], AdminToken>,
  'getAdminUpiId' : ActorMethod<[], string>,
  'getAllAdminTokens' : ActorMethod<[], Array<AdminToken>>,
  'getAllModerators' : ActorMethod<[], Array<Principal>>,
  'getCachedStatus' : ActorMethod<[], [] | [ServerStatus]>,
  'getCallerOrders' : ActorMethod<[], Array<MinecraftOrder>>,
  'getCallerRole' : ActorMethod<[], UserRoleInfo>,
  'getCallerUpiTransactions' : ActorMethod<[], Array<UpiTransaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[string], MinecraftOrder>,
  'getOrders' : ActorMethod<[], Array<MinecraftOrder>>,
  'getPendingPromotions' : ActorMethod<[], Array<PendingPromotion>>,
  'getPrincipalInfo' : ActorMethod<[], string>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getQrStatus' : ActorMethod<[string], string>,
  'getServerAddress' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[Principal], UserRoleInfo>,
  'hasPendingPromotion' : ActorMethod<[], boolean>,
  'initializePrices' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPrimaryAdminAccount' : ActorMethod<[], boolean>,
  'paymentCancel' : ActorMethod<[string], PaymentCancelResponse>,
  'paymentSuccess' : ActorMethod<
    [string, string, string],
    PaymentSuccessResponse
  >,
  'processPendingPromotions' : ActorMethod<[], undefined>,
  'promoteToAdmin' : ActorMethod<[Principal], undefined>,
  'revokeAdminToken' : ActorMethod<[string], undefined>,
  'revokeModeratorRole' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminUpiId' : ActorMethod<[string], undefined>,
  'setCachedStatus' : ActorMethod<[ServerStatus], undefined>,
  'toggleProductAvailability' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateMinecraftUsername' : ActorMethod<[string], undefined>,
  'updateProduct' : ActorMethod<
    [string, string, string, ProductCategory, bigint, boolean],
    undefined
  >,
  'validateAndRequestPromotion' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];