/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'perk' : IDL.Null,
  'rank' : IDL.Null,
  'crateKey' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const AdminToken = IDL.Record({
  'token' : IDL.Text,
  'expiresAt' : IDL.Int,
  'revoked' : IDL.Bool,
  'usedBy' : IDL.Opt(IDL.Principal),
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'used' : IDL.Bool,
});
export const UpiQrTransaction = IDL.Record({
  'status' : IDL.Text,
  'transactionReference' : IDL.Text,
  'owner' : IDL.Principal,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'qrCode' : IDL.Text,
});
export const ServerStatus = IDL.Record({
  'playerCount' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'online' : IDL.Bool,
});
export const MinecraftOrder = IDL.Record({
  'id' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'customer' : IDL.Opt(IDL.Text),
  'owner' : IDL.Principal,
  'totalAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(CartItem),
  'upiPaymentReference' : IDL.Opt(IDL.Text),
});
export const UserRoleInfo = IDL.Record({
  'isModerator' : IDL.Bool,
  'principal' : IDL.Principal,
  'isAdmin' : IDL.Bool,
});
export const UpiTransaction = IDL.Record({
  'transactionReference' : IDL.Text,
  'owner' : IDL.Principal,
  'timestamp' : IDL.Int,
  'upiId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'minecraftUsername' : IDL.Text,
});
export const PendingPromotion = IDL.Record({
  'token' : IDL.Text,
  'user' : IDL.Principal,
  'requestedAt' : IDL.Int,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'upiAmount' : IDL.Nat,
  'category' : ProductCategory,
});
export const PaymentCancelResponse = IDL.Record({
  'message' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const PaymentSuccessResponse = IDL.Record({
  'message' : IDL.Text,
  'payment' : IDL.Record({
    'status' : IDL.Text,
    'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  }),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ProductCategory, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'addUpiTransaction' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignModeratorRole' : IDL.Func([IDL.Principal], [], []),
  'confirmUpiPaymentUsingQr' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'fetchServerStatus' : IDL.Func([], [IDL.Text], []),
  'generateAdminToken' : IDL.Func([], [IDL.Text], []),
  'generateUpiQr' : IDL.Func([IDL.Vec(CartItem), IDL.Text], [IDL.Text], []),
  'getActiveAdminTokens' : IDL.Func([], [IDL.Vec(AdminToken)], ['query']),
  'getActiveUpiQrs' : IDL.Func([], [IDL.Vec(UpiQrTransaction)], ['query']),
  'getAdminToken' : IDL.Func([IDL.Text], [AdminToken], ['query']),
  'getAdminUpiId' : IDL.Func([], [IDL.Text], ['query']),
  'getAllAdminTokens' : IDL.Func([], [IDL.Vec(AdminToken)], ['query']),
  'getAllModerators' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCachedStatus' : IDL.Func([], [IDL.Opt(ServerStatus)], ['query']),
  'getCallerOrders' : IDL.Func([], [IDL.Vec(MinecraftOrder)], ['query']),
  'getCallerRole' : IDL.Func([], [UserRoleInfo], ['query']),
  'getCallerUpiTransactions' : IDL.Func(
      [],
      [IDL.Vec(UpiTransaction)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [MinecraftOrder], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(MinecraftOrder)], ['query']),
  'getPendingPromotions' : IDL.Func([], [IDL.Vec(PendingPromotion)], ['query']),
  'getPrincipalInfo' : IDL.Func([], [IDL.Text], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getQrStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getServerAddress' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [UserRoleInfo], ['query']),
  'hasPendingPromotion' : IDL.Func([], [IDL.Bool], ['query']),
  'initializePrices' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPrimaryAdminAccount' : IDL.Func([], [IDL.Bool], ['query']),
  'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
  'paymentSuccess' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [PaymentSuccessResponse],
      [],
    ),
  'processPendingPromotions' : IDL.Func([], [], []),
  'promoteToAdmin' : IDL.Func([IDL.Principal], [], []),
  'revokeAdminToken' : IDL.Func([IDL.Text], [], []),
  'revokeModeratorRole' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminUpiId' : IDL.Func([IDL.Text], [], []),
  'setCachedStatus' : IDL.Func([ServerStatus], [], []),
  'toggleProductAvailability' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateMinecraftUsername' : IDL.Func([IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ProductCategory, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'validateAndRequestPromotion' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'perk' : IDL.Null,
    'rank' : IDL.Null,
    'crateKey' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Text, 'quantity' : IDL.Nat });
  const AdminToken = IDL.Record({
    'token' : IDL.Text,
    'expiresAt' : IDL.Int,
    'revoked' : IDL.Bool,
    'usedBy' : IDL.Opt(IDL.Principal),
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'used' : IDL.Bool,
  });
  const UpiQrTransaction = IDL.Record({
    'status' : IDL.Text,
    'transactionReference' : IDL.Text,
    'owner' : IDL.Principal,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'qrCode' : IDL.Text,
  });
  const ServerStatus = IDL.Record({
    'playerCount' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'online' : IDL.Bool,
  });
  const MinecraftOrder = IDL.Record({
    'id' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'customer' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'totalAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(CartItem),
    'upiPaymentReference' : IDL.Opt(IDL.Text),
  });
  const UserRoleInfo = IDL.Record({
    'isModerator' : IDL.Bool,
    'principal' : IDL.Principal,
    'isAdmin' : IDL.Bool,
  });
  const UpiTransaction = IDL.Record({
    'transactionReference' : IDL.Text,
    'owner' : IDL.Principal,
    'timestamp' : IDL.Int,
    'upiId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'minecraftUsername' : IDL.Text,
  });
  const PendingPromotion = IDL.Record({
    'token' : IDL.Text,
    'user' : IDL.Principal,
    'requestedAt' : IDL.Int,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'upiAmount' : IDL.Nat,
    'category' : ProductCategory,
  });
  const PaymentCancelResponse = IDL.Record({
    'message' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const PaymentSuccessResponse = IDL.Record({
    'message' : IDL.Text,
    'payment' : IDL.Record({
      'status' : IDL.Text,
      'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
      'currency' : IDL.Text,
      'amount' : IDL.Nat,
    }),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ProductCategory, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'addUpiTransaction' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignModeratorRole' : IDL.Func([IDL.Principal], [], []),
    'confirmUpiPaymentUsingQr' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'fetchServerStatus' : IDL.Func([], [IDL.Text], []),
    'generateAdminToken' : IDL.Func([], [IDL.Text], []),
    'generateUpiQr' : IDL.Func([IDL.Vec(CartItem), IDL.Text], [IDL.Text], []),
    'getActiveAdminTokens' : IDL.Func([], [IDL.Vec(AdminToken)], ['query']),
    'getActiveUpiQrs' : IDL.Func([], [IDL.Vec(UpiQrTransaction)], ['query']),
    'getAdminToken' : IDL.Func([IDL.Text], [AdminToken], ['query']),
    'getAdminUpiId' : IDL.Func([], [IDL.Text], ['query']),
    'getAllAdminTokens' : IDL.Func([], [IDL.Vec(AdminToken)], ['query']),
    'getAllModerators' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCachedStatus' : IDL.Func([], [IDL.Opt(ServerStatus)], ['query']),
    'getCallerOrders' : IDL.Func([], [IDL.Vec(MinecraftOrder)], ['query']),
    'getCallerRole' : IDL.Func([], [UserRoleInfo], ['query']),
    'getCallerUpiTransactions' : IDL.Func(
        [],
        [IDL.Vec(UpiTransaction)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [MinecraftOrder], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(MinecraftOrder)], ['query']),
    'getPendingPromotions' : IDL.Func(
        [],
        [IDL.Vec(PendingPromotion)],
        ['query'],
      ),
    'getPrincipalInfo' : IDL.Func([], [IDL.Text], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getQrStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getServerAddress' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [UserRoleInfo], ['query']),
    'hasPendingPromotion' : IDL.Func([], [IDL.Bool], ['query']),
    'initializePrices' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPrimaryAdminAccount' : IDL.Func([], [IDL.Bool], ['query']),
    'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
    'paymentSuccess' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [PaymentSuccessResponse],
        [],
      ),
    'processPendingPromotions' : IDL.Func([], [], []),
    'promoteToAdmin' : IDL.Func([IDL.Principal], [], []),
    'revokeAdminToken' : IDL.Func([IDL.Text], [], []),
    'revokeModeratorRole' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminUpiId' : IDL.Func([IDL.Text], [], []),
    'setCachedStatus' : IDL.Func([ServerStatus], [], []),
    'toggleProductAvailability' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateMinecraftUsername' : IDL.Func([IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ProductCategory, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'validateAndRequestPromotion' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };